app = { name = "DysonFileSystem" }

[http]
port = "8080"

[grpc]
port = "9090"
useTLS = false
certFile = ""
keyFile = ""

[database]
dsn = "host=postgres port=5432 user=dyson password=dyson dbname=dyson_drive sslmode=disable"

[redis]
addr = "redis:6379"

[nats]
url = "nats://nats:4222"

[storage]
tempDir = "/var/lib/dyson-drive/tmp"
localDir = "/var/lib/dyson-drive/data"

[bundled]
enable = false
worker_num = 1

[auth]
target = ""
useTLS = false
tlsSkipVerify = false

[mode]
master = true
worker = true
storage = false

[files]
preferredStorage = "local"
gatewayUrl = "http://localhost:8080"
accessSecret = "change-me"

[[pools]]
id = "01SYSTEMPOOLID00000000000000"
name = "system"
default = true
hidden = true

[pools.storage]
enableSigned = true
endpoint = "/var/lib/dyson-drive/data"
bucket = "local"

[pools.billing]

[pools.policy]
publicUsable = true
